FROM node:20 AS builder
WORKDIR /app
COPY frontend .
RUN npm install && npm run build

FROM nginx:1.27.4-alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf