FROM python:3.12

WORKDIR /usr/src/app

COPY main_app/requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY main_app/ .

WORKDIR /usr/src/app/application

CMD ["sh", "-c", "celery -A application worker --loglevel=info"]